### ISSUE TITLE
Turn logger and config into singleton classes

### ISSUE THREAD

**Issue by jasonzliang** [studioml/studio#141]
It seems that logger and config are used very often in many different python files and classes. It would nice to avoid having passing around logger and config everywhere as arguements. We should make them into singleton classes where we do something like this in any python script:

```
from config import Config
x = Config()
num_workers = x.num_workers
```

**Comment by karlmutch** [comment]
singleton loggers are attracting lots of attention as anti patterns.  I am not enough of a python specialist to be able to put forward an opinion on it but searching and reading might be able to surface more information.  Thanks

**Comment by pzhokhov** [comment]
For logger in python (at least if we are using logging module) there technically already is a singleton "default" logger - that is one can do the following:

     import logging
     logging.basicConfig()
     logging.error('aaa')  # prints ERROR:root:aaa

the point of passing loggers around is to be able to distinguish between source of messages by using logger names. On the other hand, due to GIL in python one does not really have to worry that multiple loggers will have any sort of race condition with each other. 
As for config - there can be multiple different configs (at least in principle) in the module. Good example would be a local worker - it receives config from a message in the queue, but also has it's own config at the startup. Besides, I feel that in the end of the day we should be only passing the parts of the config necessary for the submodules to them, and not the entire global config. 

As such, I'll close this issue for now, but feel free to reopen it with more arguments.
