### ISSUE TITLE
tag releases and have it match pip installed version

### ISSUE THREAD

**Issue by arshak** [studioml/studio#166]
Users need to understand what version of studio they have installed.

We should tag releases in github and have it match the pip intalls

pip installed version looks like this currently:
studioml (0.0.0)

**Comment by karlmutch** [comment]
The env var TRAVIS_TAG is being used, however at this time we are not using 'git tag' as we don't have a CI/CD pipeline formally done> we also done have any process/statement on release management, for example who allocates version numbers etc for example.  This means that I am using hand coded versions such as ...

Installing collected packages: studioml
  Found existing installation: studioml 0.0.1.post17
    Uninstalling studioml-0.0.1.post17:
      Successfully uninstalled studioml-0.0.1.post17
  Running setup.py develop for studioml
Successfully installed studioml

If you are seeing 0.0.0 then there is something up, that should not be happening unless you are doing a local pip install -e . which is the correct behavior in that case because you are using unversioned artifacts.

Thanks

**Comment by pzhokhov** [comment]
We are releasing tagged versions automatically from travis on successful builds; non-tagged versions are also released with .-post<distance> suffix.
