### ISSUE TITLE
Question: How do you manage the experiments

### ISSUE THREAD

**Issue by yuvval** [studioml/studio#196]
Hi 

I recently discovered this project and it looks really good.
I was wondering how do you manage the experiments:

Is there a way to delete unnecessary results (e.g. due to bugs)? 

What happens if some run crashes? 
-Would it be flagged as failed? 
-Would another machine in the queue take over it and re-run it?  

Can I "kill" some execution of an hyper-param search experiment ?

Whats the best-practice during development time, when the model changes, but the script name is the same? I.e. how to differentiate the between version of the model? 
 
Thanks!

**Comment by pzhokhov** [comment]
Hi @yuvval ! 
The results that you don't need you can delete either via UI (you can select multiple rows and then click "delete" button, "(De)Select all" button may also come handy. If you need some sort of filtering and deletion, you can use the CLI - `studio runs list` will show your runs, you can the filter them, and delete them via `studio runs kill`

If the run crashes (i.e. fails with exception from within your script), it would be still marked as finished.  We can add a feature that would check whether user script has finished normally or with an exception. 
Another machine won't overtake the the experiment if the crash was within the user script (and I don't think it should - because then if, for instance, the user script contains a syntax error, the executor machines will keep trying to re-run it. 
However, another machine will pick up the experiment if the problem was external - i.e. the instance was shut down while experiment was running, spot instance was taken away, or studio.ml code itself crashed abruptly. 

As for killing the entire hyperparameter search experiment - hyperparameter search experiments are created as projects that contain all individual runs. You can simply delete all experiments from that project (either by CLI or using web UI)

Best practice for keeping track of models if you have the same script name (in my opinion, I'll invite @arshak to express his thoughts on that) is to use git commits. If you run studio from a clean git commit, it will store that info and display it in the UI and add a link to github, so you'll be able to tell exactly which version of the code a particular experiment was run from (even without downloading the file and looking at it). You can then also look at the commit messages to see the summary of what was special about that particular commit. 

Hope that helps!
