### ISSUE TITLE
Can't run experiment.. KeyError: 'resources_needed' in studio/studio/runner.py", line 228

### ISSUE THREAD

**Issue by shaneh2** [studioml/studio#218]
Hi, I have managed to install studioml and open up the UI in my browser and login using my Google Account, but I can't run an experiment on my machine and the error message seems cryptic. Any help would be greatly appreciated.

```
studio run train_mnist_keras.py
Traceback (most recent call last):
  File "/Users/shanework/miniconda2/bin/studio-run", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/shanework/studio/studio/scripts/studio-run", line 3, in <module>
    runner.main()
  File "/Users/shanework/studio/studio/runner.py", line 228, in main
    resources_needed = parse_hardware(runner_args, config['resources_needed'])
KeyError: 'resources_needed'
```

**Comment by tcql** [comment]
I ran into this as well. It seems for some reason the running is having trouble locating the default config. I fixed by coping the `default_config.yaml` from this repo into the directory I was working in and running like so: 

```
studio run --config=default_config.yaml train_mnist_keras.py
```

**Comment by pzhokhov** [comment]
The reason why this is happening is because the format of the config file has changed a little bit recently; at the same time, when you re-install studio (either from github or pypi package), the config file in ~/.studioml/config.yaml is not being overwritten (if present). 
Thus, if happens, try getting the latest studio code, deleting ~/.studioml/config.yaml and reinstalling studio. 
I'll close this issue for now, but please don't hesitate to re-open it again or open a new one if this / similar problem keeps happening.
