### ISSUE TITLE
Use wget for downloading files

### ISSUE THREAD

**Issue by jasonzliang** [studioml/studio#227]
Peter and I have observed that using wget to download files is significantly faster than the current approach which is to use python requests library.

**Comment by karlmutch** [comment]
Is this with AWS or Google cloud storage.  Enhanced downloads are supported by the standard libraries such as boto3 but I think need to be enabled explicitly to be used.

**Comment by pzhokhov** [comment]
that's for the case when file download is over http (for example, firebase storage actually uses http underneath, even though it refers to the google storage); or when download is from user-specified location (I remember we agreed that that's not a very advised thing to do anyways due to lack of metadata). Incidentally, do you know how to explicitly enable fast download using boto3 or google.cloud.storage?

**Comment by karlmutch** [comment]
S3 - http://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html
        http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETaccelerate.html

set it in your file ~/.aws/config
s3 = use_accelerate_endpoint = true

Google - Has a transfer service that does this, however I have not used it as I am concentrating on S3 for deployments

**Comment by pzhokhov** [comment]
Thanks!

**Comment by karlmutch** [comment]
I think ? this can be closed.  @pzhokhov please reopen if needed
