### ISSUE TITLE
Studio support for singularity

### ISSUE THREAD

**Issue by arshak** [studioml/studio#268]
I want Studio to support singularity containers (mostly because of caffe and torch models are a headache on bare metal) 

studio run mnist.py --container my_singularized_image

Container location can be local or gcs/s3 URLs 

Also would be great to support

studio serve mnist.py --container caffe_image

**Comment by pzhokhov** [comment]
We might need to make some assumptions about the structure of files in the container... I see 3 paths here:
1. self-runnable containers (in which case container can run whatever the heck it wants, not even necessarily python - and the command line becomes more like `studio run --container my_image`
2. there is a certain location within the container where the script is supposed to be, and we are running python. 

@karlmutch, what are your thoughts on this?

**Comment by karlmutch** [comment]
This will be driven by the container.

If the user specifies a %runscript inside the def file used to build the
tar archive then that is what they get.  This works by overridding what the
standard studioml command line would otherwise be doing.

The second way is when the python command is left to its own devices as
happens today and is done by the runner building the cmd line.

In both cases the a process occurs whereby the container is augmented by
the runner adding an overlay that is composed of the extracted artifacts
and the existing experiment directory hierarchy. Because its an overlay the
runners can do their normal uploads etc as the experiment progresses.  For
all other directories the runner will mask them out so the users tasks do
not see the other parts of the file system.

The runner is then responsible for generating experiment directories in
their own trees and then binding each tree to its own running clients.

The base containers then become artifacts.  The means that a combination of
the current workspace and a base layer would be combined.  The only trigger
needed to activate singularity is the present of the specially named
artifact, in all other ways the JSON is indistinguishable from a python
specific virtualenv json payload.

There are many other modes involving sandboxes etc which we could also use
if the mood takes us.

Thanks,
Karl

**Comment by pzhokhov** [comment]
@karlmutch do I understand correctly that singularity only runs on linux? So to run it on mac we'll need additional VM in the middle? Singularity installation suggests vagrant, but I assume any linux vm should work?

**Comment by karlmutch** [comment]
Yes I agree. Mac will only ever be a development platform as long as OSX is
around.

**Comment by pzhokhov** [comment]
On the python side should be addressed by this PR: https://github.com/studioml/studio/pull/278. 
No support for serving just yet (because there is no serving without singularity either)
